import './globals.css';
import type { Metadata } from 'next';
import { AdditionalProviders } from '@/components/additional-providers';
import { Inter } from 'next/font/google';
import '@/configs/prime-theme/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import { Authentication } from '@/components/authentication';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Webinar Blue Cap',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AdditionalProviders>
          <Authentication>{children}</Authentication>
        </AdditionalProviders>
      </body>
    </html>
  );
}
