import type { Metadata } from "next";
import "./globals.css";
import { AdditionalProviders } from "@/components/additional-providers/additional-providers";

export const metadata: Metadata = {
  title: "Webinar Blue Cap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AdditionalProviders>
          {children}
        </AdditionalProviders>
      </body>
    </html>
  );
}
